# Generated by Django 2.1.5 on 2019-01-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Project', max_length=64, primary_key=True, serialize=False),
        ),
    ]
